# Use an official Node.js runtime
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port (match your Express app)
EXPOSE 3000

# Start the backend server
CMD ["npm", "run" ,"start"]
