//get all posts
GET https://node38.cs.colman.ac.il/posts

###

POST https://node38.cs.colman.ac.il/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc0MWNkYWFiYjFhYjVmMTgzMGIxOTciLCJpYXQiOjE3MzU2NjMwNDIsImV4cCI6MTczNTY2NjY0Mn0.680KF603pqonag4GBQIWwYFWJOep1J7z-ai-AdkDHR0
Content-Type: application/json

{
    "title": "title",
    "content": "content",
    "owner": "owner"
}

###

POST https://node38.cs.colman.ac.il/auth/login
Content-Type: application/json

{
    "email": "example@mail.com",
    "password": "1234"
}

###

POST https://node38.cs.colman.ac.il/auth/register
Content-Type: application/json

{
    "email": "example@mail.com",
    "password": "1234"
} 

###


POST https://node38.cs.colman.ac.il/auth/logout
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc0MjA3NzRmNzRiMThkNGE4ZGE2NWMiLCJyYW5kb20iOiIwLjA1OTQxNjg4MTgyODI2MDEwNCIsImlhdCI6MTczNTY2MzgyM30.Vhv7C8Fg-erCtLRsuzy0iZUPXjHVhwz2X6F0up1Qupc

###

POST https://node38.cs.colman.ac.il/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc0MzM0MjcwYmJjMzQ2OTNiNWZkNmYiLCJyYW5kb20iOiIwLjAxODE3NTM1MTM2MDE3MTAxIiwiaWF0IjoxNzM1NjY4NTQ5fQ.LSztMFlxx5HN6PYD0OiV8OIFWLMOHnESC5G4_qCRy6Q"
}